title: 'جنسیت ها'
modelClass: Sepehr\Details\Models\Sex
list: $/sepehr/details/models/sex/columns.yaml
recordUrl: 'sepehr/details/sex/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
