title: 'پیام ها'
modelClass: Sepehr\Message\Models\Message
list: $/sepehr/message/models/message/columns.yaml
recordUrl: 'sepehr/message/messages/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
defaultSort:
    column: id
    direction: asc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
