title: 'انواع روش های پرداخت'
modelClass: Sepehr\Details\Models\PaymentType
list: $/sepehr/details/models/paymenttype/columns.yaml
recordUrl: 'sepehr/details/paymenttypes/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
defaultSort:
    column: id
    direction: asc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
