title: 'سرویس های ویژه'
modelClass: Sepehr\Details\Models\SpecialService
list: $/sepehr/details/models/specialservice/columns.yaml
recordUrl: 'sepehr/details/specialservices/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
