title: 'انواع وزن مرسوله'
modelClass: Sepehr\Details\Models\Weight
list: $/sepehr/details/models/weight/columns.yaml
recordUrl: 'sepehr/details/weights/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
