name: 'انواع وزن مرسوله'
modelClass: Sepehr\Details\Models\Weight
form: $/sepehr/details/models/weight/fields.yaml
defaultRedirect: sepehr/details/weights
create:
    title: 'ایجاد نوع وزن'
    redirect: 'sepehr/details/weights/update/:id'
    redirectClose: sepehr/details/weights
    flashSave: 'نوع وزن با موفقیت ایجاد شد'
update:
    title: 'ویرایش نوع وزن'
    redirect: sepehr/details/weights
    redirectClose: sepehr/details/weights
    flashSave: 'نوع وزن با موفقیت ویرایش شد'
    flashDelete: 'نوع وزن با موفقیت حذف شد'
preview:
    title: 'پیش نمایش نوع وزن'
