title: 'پیش شماره کشورها'
modelClass: Sepehr\Details\Models\CountryCode
list: $/sepehr/details/models/countrycode/columns.yaml
recordUrl: 'sepehr/details/countrycodes/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
