
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/rantiz/gateway/models/transaction/columns.yaml

# Model Class name
modelClass: Rantiz\Gateway\Models\Transaction

# List Title
title: rantiz.gateway::lang.form.view.list_title

# Link URL for each record
recordUrl: 'rantiz/gateway/lists/preview/:id'

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 25

# Displays the list column set up button
showSetup: true

# Displays the sorting link on each column
showSorting: true

# Default sorting column
defaultSort:
    column: payment_date
    direction: desc

# Display checkboxes next to each record
showCheckboxes: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt

# Filter widget configuration
filter: config_filter.yaml
