title: 'سرویس پست'
modelClass: Sepehr\Service\Models\Service
list: $/sepehr/service/models/service/columns.yaml
recordUrl: 'sepehr/service/services/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
