title: 'انواع زمان توزیع'
modelClass: Sepehr\Details\Models\DistributionTime
list: $/sepehr/details/models/distributiontime/columns.yaml
recordUrl: 'sepehr/details/distributiontimes/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
